<template>
    <div class="news-detail">
        <header class="title">
            <h2>{{data.title}}</h2>
        </header>
        <div class="article-info">
            <span class="author-info">
                <img src="/static/img/cnn.jpg" alt="">
                <span class="author">CNN</span>
            </span>
            <span class="date">{{date}}</span>
        </div>
        <div class="player-wrap">
            <mini-player :url="data.mp3"></mini-player>
        </div>
        <div id="content" @touchstart="touchStart" @touchend="touchEnd" v-html="newcontent" :class="[{ 'fixed': showDict }, 'content']">
        </div>
        <word-card :word="searchWord" v-show="showCard" @getExplain="getExplain" ></word-card>
        <tool-bar :top="toolTop" :star="starIcon" :left="toolLeft" v-show="showTool" @deleteWord='deleteWord' @addWord='addWord' @searchWord='searchWord'></tool-bar>
        <div class="side-bar">
            <ul>
                <li @click="toTop">
                    <img src="/static/img/top.svg" alt="">
                </li>
                <li @click="showDict = !showDict">
                    <img src="/static/img/dict.svg" alt="">
                </li>
            </ul>
        </div>
        <word-book v-show="showDict" @hideBook="showDict = false" :words="words" @deleteWord='deleteWord'></word-book>
    </div>
</template>

<script>
import miniPlayer from './miniPlayer'
import toolBar from './toolBar'
import wordCard from './wordCard'
import wordBook from './wordBook'
const STAR_O = "/static/img/starO.svg"
const STAR = "/static/img/star.svg"

export default {
    name: 'NewsDetail',
    components: { miniPlayer, wordCard, toolBar, wordBook },
    data() {
        return {
            data: {
                title: 'CNNSN-2017-06-02-CNN-Student-News',
                script: ' (CNN Student News) -- June 2, 2017<br><br><br>The Paris Climate Accord; Effort to Protect Farm Workers<br><br><br><br>THIS IS A RUSH TRANSCRIPT. THIS COPY MAY NOT BE IN ITS FINAL FORM AND MAY BE UPDATED.<br><br>***<br><br>CARL AZUZ, CNN 10 ANCHOR: Fridays are awesome. I`m Carl Azuz and this is our last show of the season for CNN 10 -- a free 10-minute show that explains world events.<br><br>We`re starting with news about the Paris climate accord. Yesterday, U.S. President Donald Trump announced that America would be withdrawing from the international agreement. But, first, what is it?<br><br>The Paris accord was named for the French capital where the deal was made in 2015. It was a major priority of President Barack Obama who led the U.S. at that time. One hundred ninety-five out of 197 countries signed on to the agreement. In doing so, they promised to reduce their greenhouse gas emissions.<br><br>The nations themselves got to decide by how much they`d actually do that, and the accord was not legally binding. There`s no penalty for a country that doesn`t meet its pledge.<br><br>Current President Trump was not required to keep the U.S. in the deal and he said staying would have cost millions of American jobs.<br><br>(BEGIN VIDEO CLIP)<br><br>DONALD TRUMP, PRESIDENT OF THE UNITED STATES: As president, I can put no other consideration before the wellbeing of American citizens. The Paris climate accord is simply the latest example of Washington entering into an agreement that disadvantages the United States.<br><br>(END VIDEO CLIP)<br><br>AZUZ: President Trump added that the U.S. would start negotiations for a new deal that was more fair to Americans.<br><br>Critics like former President Obama said President Trump rejected the future by leaving the agreement. And the leaders of several other countries said they`d stick to the Paris accord and said it was harmful for the U.S. to leave. Most climate scientists say it`s extremely likely that greenhouse gas emissions, which are generated by human activity contribute to global warming. But some critics say the claims surrounding these emissions are over-exaggerated and that climate modeling is not an exact science.<br><br>The U.S. withdrawal from the Paris accord won`t happen immediately. It could take months or years to complete the process.<br><br>(BEGIN VIDEO CLIP)<br><br>AZUZ (voice-over): Ten-second trivia:<br><br>After California and Texas, what is the third-most populated state in America?<br><br>Florida, New York, Pennsylvania, or Washington?<br><br>The answer is Florida, which has a population of more than 20 million people.<br><br>(END VIDEO CLIP)<br><br>AZUZ: Human trafficking might include slavery, forced labor, the practice of buying and selling people. It affects almost every country on earth and specifically today, we`re talking about trafficking accusations in the U.S. state of Florida. You`ll soon hear about a program that aims to protect farm workers against this.<br><br>Not all food industry businesses participate in the program. It does cost them more, a penny per pound of tomatoes they buy. And that`s supposed to go directly to farm workers, some critics argue that the farm should be responsible for paying its workers more, not the businesses themselves in a separate payment.<br><br>Still, for the people CNN spoke to, there are tangible benefits to the program.<br><br>(BEGIN VIDEOTAPE)<br><br>REPORTER: Immokalee, Florida, hot, humid, and home to thousands of migrant workers who board buses early, every morning, bound for tomato farms scattered throughout the region.<br><br>Immokalee is the epicenter of tomato production in the United States. Florida produces 90 percent of the country`s winter tomatoes. It also used to be ground zero for modern day slavery in agriculture.<br><br>LAURA GERMINO, COALITION OF IMMOKALEE WORKERS: We found out that workers were being held by armed guars, you know, prevented from leaving, pistol-whipped, some sexually assaulted.<br><br>REPORTER: Laura Germino is one of the founders of the coalition of Immokalee workers, or CIW, a grassroots non-profit that begun in 1993 to improve wages and working conditions of migrant farm workers.<br><br>GERMINO: Initially, it was not an anti-slavery organization or anti-human trafficking organization, but in the course of our outreach, we begin to come across situations where workers were being held against their will.<br><br>REPORTER: Since then, the CIW`s anti-slavery program has uncovered and helped the U.S. government prosecutes several horrific cases of forced labor on tomato farms.<br><br>In one of those cases, just ten years ago, farm workers were locked inside a truck at night.<br><br>GERMINO: It was a dozen workers housed in a windowless box truck, forced to be in there at night, sleeping there at night, used the bathroom in there at night. One of them held out his hands and you could see the marks from the chains, which his wrist had been chained with.<br><br>REPORTER: That case was so shocking, CIW decided to buy a box truck that was the exact make and model as the one used in the case, and turned it into a model museum, highlighting other cases of forced labor from the past 20 years. Today, the CIW has a staff of 17 people, nearly all of them former migrant farm workers themselves and their focus is no longer uncovering cases of slavery. It`s preventing it from happening in the first place.<br><br>GERMINO: Forced labor has been virtually eradicated and if it were to take root, it would be identified and dealt with really quickly.<br><br>REPORTER: They do that through an innovative initiative called the Fair Food Program. Participating growers allow CIW staff to come on to their farms and hold mandatory education sessions for all workers. They`re given booklets that outlined their rights and a hotline to call if they experience violations.<br><br>The growers also agreed to regular third party inspections of their farms. A team of auditors speaks confidentially with at least 50 percent of workers to insure their rights are being respected.<br><br>Laura Safer Espinosa is a former Supreme Court justice for the state of New York. She now spends her retirement in Florida running the Fair Food Standards Council which oversees the audits.<br><br>LAURA SAFER ESPINOSA, FAIR FOOD STANDARDS COUNCIL: Places that were called ground zero from modern day slavery by federal prosecutors a few years ago are now cited by national and international human rights experts as the best work environment in U.S. agriculture.<br><br>REPORTER: And there are real market consequences at the top of the supply chain if violations are found. That`s because many of the largest buyers of tomatoes have also joined the program, agreeing to purchase tomatoes only from farms that are part of the agreement. The Fair Food Program started in Florida, and now covers seven states in the eastern part of the U.S.<br><br>Carlos Hernandez spends a tomato growing season in Florida. In the off- season, he travels to the western U.S. where he says it`s much different.<br><br>CARLOS HERNANDEZ (through translator): Sometimes when you don`t work fast enough, they threaten to fire you. Well, that doesn`t happen here. There are better protections here.<br><br>ESPINOSA: When we get calls from outside the Fair Food Program, it is heartbreaking.<br><br>REPORTER: There are roughly 30,000 people currently working on Fair Food Program farms and receiving all the protections and benefits outlined in the agreement. But they`re still a long way to go to bringing the rest of the country on board.<br><br>(END VIDEOTAPE)<br><br>AZUZ: Well, what better way to end the season than by taking a trip to the beach, and not just any beach, Britain`s Weston Super Mare Beach, whose muddy sand is said to be perfect for sand sculpting.<br><br>The artists start by packing together an extremely hard block of sand and then shaping the sculpture out of it. They say there`s no frame, glue or concrete used, that these massive works take about a week to build and, of course, this guy gets extra credit.<br><br>You`ll need more than a grain of talent. You got to be able to work well with your sands and there`s no way for the art to weather a storm. If it rains, all efforts are a total wash. Still, they certainly sandgage a sculp following as long as they`re still sanding.<br><br>I`m Carl Azuz. Thank you for being the best and biggest audience we have ever had. From our staff here at CNN 10, we hope you have a wonderful summer ahead and we`ll look forward to seeing you again on August 14th.<br><br>END<br>',
                mp3: 'http://www.listeningexpress.com/cnn/cnnstudentnews/CNNSN%202017-06-02%20CNN%20Student%20News.mp3',
            },
            curExplain:'',
            curword:'word',
            showCard: false,
            showTool: false,
            toolTop: '200',
            toolLeft: '100',
            searchWord: '',
            showDict: false,
            words: {},
            tmpWords: {},
            starIcon:STAR_O,
            date:''
        }
    },
    computed: {
        //把内容转换成<span>词</span>的形式
        newcontent() {
            var ctx = this.data.script;
            var reg = /\b(\w+)\b/g;
            var self = this;
            ctx = ctx.replace(reg, function (a, b, c) {
                if (a === 'br') {
                    return a;
                }
                else {
                    let word = a.toLowerCase();
                    if(word in self.words){
                        return '<span data-id=' + word + ' class="hl">' + a + '</span>';
                    }
                    return '<span data-id=' + word + '>' + a + '</span>';
                }
            });
            return ctx;
        }
    },
    methods: {
        setItem(name,item){
            window.localStorage.setItem('news_'+name,JSON.stringify(item));
        },
        getItem(name){
            return JSON.parse(window.localStorage.getItem('news_'+name));
        },
        getExplain(e) {
            console.log('ex' + e);
            this.curExplain= e;
            this.tmpWords[this.curword] = {name:this.curword,explain:this.curExplain};
            console.log(this.tmpWords);
        },
        // 每次触摸开始就开始计算时间
        touchStart(e) {
            this.time = +new Date();
            this.showCard = false;
            var target = e.target;
            this.showTool = false;
            var toolWidth = 140;
            if (target.tagName === 'SPAN' && target.classList.contains('hl')) {
                this.log(target.offsetTop);
                this.log(target.offsetHeight);
                this.curword = target.innerText.toLowerCase();
                if(this.curword in this.words){
                    console.log('star');
                    this.starIcon = STAR;
                }else{
                    this.starIcon = STAR_O;
                    console.log('star0');
                }
                this.showTool = true;
                this.toolTop = target.offsetTop + target.offsetHeight + 5;
                this.toolLeft = target.offsetLeft + target.offsetWidth / 2 - toolWidth / 2;
                this.toolLeft = this.toolLeft < 0 ? 0 : this.toolLeft;
                this.toolLeft = this.toolLeft + toolWidth > window.innerWidth ? window.innerWidth - toolWidth : this.toolLeft;
                
                // console.log(this.curword);
                if(this.tmpWords[this.curword]){
                    this.curExplain= this.tmpWords[this.curword].explain;
                }
            }
        },
        toTop() {
            window.scrollTo(0, 0);
        },

        // 超过400ms的时间表示长按
        touchEnd(e) {
            if (+new Date() - this.time > 400) { //大于400ms
                if (e.target.id !== 'content') {
                    var target = e.target;

                    var nodeList = document.querySelectorAll('[data-id="' + target.dataset.id + '"]');
                    for (var i = 0; i < nodeList.length; i++) {
                        nodeList[i].classList.add('hl');
                    }
                    // 查单词
                    this.curword = target.innerText.toLowerCase();
                    this.searchWord = this.curword;
                    this.showCard = true;   // 显示单词卡片
                }
            }
        },
        play() {
            var scrllTop = window.scrollY;
            var player = document.querySelector('.player-wrap');
            if (player && scrllTop > player.offsetTop) {
                if (!player.classList.contains('fixed')) {
                    // console.log(scrllTop);
                    player.classList.add('fixed');
                }
            } else if (player && player.classList.contains('fixed')) {
                // console.log(scrllTop);
                player.classList.remove('fixed');
            }
        },
        deleteWord(name) {
            this.showTool = false;
            var name = name || this.curword;
            var nodeList = document.querySelectorAll('[data-id="' + name + '"]');
            for (var i = 0; i < nodeList.length; i++) {
                nodeList[i].classList.remove('hl');
            }
            if(name in this.words){
                this.$delete(this.words,name);
                this.setItem('vocs',this.words);
            }
        },
        addWord() {
            this.$set(this.words,this.curword,{name:this.curword,explain:this.curExplain});
            this.setItem('vocs',this.words);
            // this.words[this.curword] = ;
            // this.words.push({name:this.curword,explain:this.curExplain});
        },
        searchWord() {
            this.log('search');
            this.searchWord = this.curword;
            this.showCard = true;   // 显示单词卡片
        }
    },
    mounted() {
        window.addEventListener('scroll', this.play);
    },
    created() {
        window.scrollTo(0, 0);
        var url = this.$route.params.data;

        var self = this;
        this.date = this.$route.params.date;
        this.words = this.getItem('vocs') || {};
        console.log(this.getItem('vocs'));
        this.$http({
            method: 'get',
            url: url
        }).then(function (data) {
                if (data.status === 200) {
                    self.data = data.data;
                }
            }).catch(function (err) {
                console.log(err);
            })
    }
}  
</script>

<!-- Add "scoped" attribute to limit CSS to this component only -->
<style scoped>
.news-detail {
    padding: 20px;
}

.title h2 {
    font: 20px/1.4em bold a;
    margin-bottom: 20px;
}

.article-info {
    font: 14px/1.4em a;
    border-bottom: 1px solid #eee;
}

.author-info {
    overflow: hidden;
    display: inline-block;
}

.side-bar {
    position: fixed;
    right: 15px;
    bottom: 20px;
    width: 40px;
}

.side-bar ul li {
    list-style: none;
    border-radius: 50%;
    height: 20px;
    width: 20px;
    padding: 10px;
    border: 1px solid #ddd;
    margin-bottom: 10px;
    background: rgba(223, 223, 223, 0.58);
}

.side-bar img {
    width: 100%;
    height: 100%;
}


.player-wrap {
    position: absolute;
    margin-top: 20px;
    width: 100%;
    margin-left: -20px;
}

.player-wrap.fixed {
    position: fixed;
    top: 0;
    margin-top: 0px;
}

.author-info .author {
    vertical-align: middle;
    color: #aaa;
}

.author-info img {
    height: 25px;
    margin-right: 10px;
    vertical-align: middle;
}

.date {
    float: right;
    right: 0;
    color: #e8bf21;
}

.content {
    color: #444;
    margin-top: 40px;
    font: 16px/1.8em a;
    font-family: Arial;
}
.content.fixed{
    position: fixed;
}
</style>
